# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'native_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-sdk-integration
  flutter_application_path = '../native_module' # Adjust this path accordingly
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  # pod 'Flutter', :path => '../native_module'
  # flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end
