name: demo_poc
description: A Flutter package that provides a demo of various POCs (Proof of Concepts) with reusable widgets and components..
version: 1.0.0+4
repository: https://github.com/TejeshT/flutter_todo_list

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
